# -*- coding: utf-8 -*-
"""MiniProject8thSem25_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M-CYf16cycryJ5VUzFGKYC5ZJtAQpknD
"""

from google.colab import drive

drive.mount('/content/drive')

import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("✅ Using device:", device)

!pip install langchain

!pip install langchain_community

!pip install -U langchain langchain-community faiss-cpu sentence-transformers pypdf pdfminer.six pdfplumber \transformers accelerate bitsandbytes gradio rank_bm25 scikit-learn joblib

!pip install -U transformers

!pip install -q langchain chromadb unstructured pypdf sentence-transformers torch transformers accelerate
!pip install -q faiss-cpu

!pip install pi_heif unstructured_inference pdf2image PyMuPDF pdfplumber

!pip install streamlit pyngrok

!pip install pymatgen

from pymatgen.ext.matproj import MPRester
import pandas as pd

!pip install mp-api

# API key
API_KEY = "your-api-key"
from mp_api.client import MPRester

from mp_api.client import MPRester
import pandas as pd


with MPRester(API_KEY) as mpr:
    data = mpr.materials.summary.search(
        num_elements=(1, 10),
        is_stable=True,
        fields=[
            "formula_pretty", "elements", "density", "band_gap",
            "formation_energy_per_atom", "energy_above_hull", "volume",
            "e_total", "e_ionic", "e_electronic", "shear_modulus", "bulk_modulus",
            "total_magnetization", "is_metal", "is_magnetic", "symmetry"
        ],
        chunk_size=200
    )

    materials = []
    for entry in data:
        shear = entry.shear_modulus or {}
        bulk = entry.bulk_modulus or {}

        materials.append({
            "compound": entry.formula_pretty,
            "elements": "-".join(str(e) for e in entry.elements),
            "density": entry.density,
            "band_gap": entry.band_gap,
            "formation_energy_per_atom": entry.formation_energy_per_atom,
            "energy_above_hull": entry.energy_above_hull,
            "volume": entry.volume,
            "shear_modulus_voigt": shear.get("voigt"),
            "shear_modulus_reuss": shear.get("reuss"),
            "shear_modulus_vrh": shear.get("vrh"),
            "bulk_modulus_voigt": bulk.get("voigt"),
            "bulk_modulus_reuss": bulk.get("reuss"),
            "bulk_modulus_vrh": bulk.get("vrh"),
            "total_magnetization": entry.total_magnetization,
            "is_metal": entry.is_metal,
            "is_magnetic": entry.is_magnetic,
            "dielectric_total": entry.e_total,
            "dielectric_ionic": entry.e_ionic,
            "dielectric_electronic": entry.e_electronic,
            "symmetry": entry.symmetry.symbol if entry.symmetry else None
        })

df = pd.DataFrame(materials)
df.to_csv("cleaned_materials_data_v2.csv", index=False)
print("✅ Updated dataset saved as 'cleaned_materials_data_v2.csv'")

df.head(10)

from itertools import chain

unique_elements = set(chain(*df['elements'].apply(lambda x: x.split('-'))))
# Assuming elements are stringified lists
print(f"Unique elements in dataset: {sorted(unique_elements)}")
print(f"Number of unique elements: {len(unique_elements)}")

import pandas as pd

df = pd.read_csv("/content/cleaned_materials_data_v2.csv")

df_cleaned = df.drop_duplicates()
threshold = 0.8
missing_fraction = df_cleaned.isnull().mean()
cols_to_drop = missing_fraction[missing_fraction > threshold].index
df_cleaned = df_cleaned.drop(columns=cols_to_drop)

numeric_cols = df_cleaned.select_dtypes(include='number').columns
df_cleaned[numeric_cols] = df_cleaned[numeric_cols].fillna(df_cleaned[numeric_cols].median())

categorical_cols = df_cleaned.select_dtypes(include='object').columns
df_cleaned[categorical_cols] = df_cleaned[categorical_cols].fillna('Unknown')

# Standardizing column names (strip, lowercase, and replace spaces with underscores)
df_cleaned.columns = df_cleaned.columns.str.strip().str.lower().str.replace(" ", "_")

# Fixing formatting in the 'elements' column (sorting elements alphabetically)
if 'elements' in df_cleaned.columns:
    df_cleaned['elements'] = df_cleaned['elements'].apply(
        lambda x: "-".join(sorted(x.split("-"))) if isinstance(x, str) else x
    )
df_cleaned.to_csv("processed_data.csv", index=False)

print("✅ Cleaned data saved to 'processed_data.csv'")

df_cleaned.head(10)

import pandas as pd

df = pd.read_csv("/content/processed_data.csv")

# correlation of 'band_gap' with 'is_metal'
df[['band_gap', 'is_metal']].groupby('is_metal').describe()

!pip install feedparser scholarly requests beautifulsoup4 PyPDF2 tqdm concurrent-log-handler
import os
import requests
import feedparser
import pandas as pd
import time
from tqdm import tqdm
import pickle
from concurrent.futures import ThreadPoolExecutor
import PyPDF2
os.makedirs('/content/data/papers', exist_ok=True)
os.makedirs('/content/data/textbooks', exist_ok=True)
os.makedirs('/content/data/other', exist_ok=True)
ELEMENTS = {
    'Ac': 'Actinium', 'Ag': 'Silver', 'Al': 'Aluminum', 'Am': 'Americium',
    'Ar': 'Argon', 'As': 'Arsenic', 'At': 'Astatine', 'Au': 'Gold',
    'B': 'Boron', 'Ba': 'Barium', 'Be': 'Beryllium', 'Bh': 'Bohrium',
    'Bi': 'Bismuth', 'Bk': 'Berkelium', 'Br': 'Bromine', 'C': 'Carbon',
    'Ca': 'Calcium', 'Cd': 'Cadmium', 'Ce': 'Cerium', 'Cf': 'Californium',
    'Cl': 'Chlorine', 'Cm': 'Curium', 'Cn': 'Copernicium', 'Co': 'Cobalt',
    'Cr': 'Chromium', 'Cs': 'Cesium', 'Cu': 'Copper', 'Db': 'Dubnium',
    'Ds': 'Darmstadtium', 'Dy': 'Dysprosium', 'Er': 'Erbium', 'Es': 'Einsteinium',
    'Eu': 'Europium', 'F': 'Fluorine', 'Fe': 'Iron', 'Fl': 'Flerovium',
    'Fm': 'Fermium', 'Fr': 'Francium', 'Ga': 'Gallium', 'Gd': 'Gadolinium',
    'Ge': 'Germanium', 'H': 'Hydrogen', 'He': 'Helium', 'Hf': 'Hafnium',
    'Hg': 'Mercury', 'Ho': 'Holmium', 'Hs': 'Hassium', 'I': 'Iodine',
    'In': 'Indium', 'Ir': 'Iridium', 'K': 'Potassium', 'Kr': 'Krypton',
    'La': 'Lanthanum', 'Li': 'Lithium', 'Lr': 'Lawrencium', 'Lu': 'Lutetium',
    'Lv': 'Livermorium', 'Mc': 'Moscovium', 'Md': 'Mendelevium', 'Mg': 'Magnesium',
    'Mn': 'Manganese', 'Mo': 'Molybdenum', 'Mt': 'Meitnerium', 'N': 'Nitrogen',
    'Na': 'Sodium', 'Nb': 'Niobium', 'Nd': 'Neodymium', 'Ne': 'Neon',
    'Nh': 'Nihonium', 'Ni': 'Nickel', 'No': 'Nobelium', 'Np': 'Neptunium',
    'O': 'Oxygen', 'Og': 'Oganesson', 'Os': 'Osmium', 'P': 'Phosphorus',
    'Pa': 'Protactinium', 'Pb': 'Lead', 'Pd': 'Palladium', 'Pm': 'Promethium',
    'Po': 'Polonium', 'Pr': 'Praseodymium', 'Pt': 'Platinum', 'Pu': 'Plutonium',
    'Ra': 'Radium', 'Rb': 'Rubidium', 'Re': 'Rhenium', 'Rf': 'Rutherfordium',
    'Rg': 'Roentgenium', 'Rh': 'Rhodium', 'Rn': 'Radon', 'Ru': 'Ruthenium',
    'S': 'Sulfur', 'Sb': 'Antimony', 'Sc': 'Scandium', 'Se': 'Selenium',
    'Sg': 'Seaborgium', 'Si': 'Silicon', 'Sm': 'Samarium', 'Sn': 'Tin',
    'Sr': 'Strontium', 'Ta': 'Tantalum', 'Tb': 'Terbium', 'Tc': 'Technetium',
    'Te': 'Tellurium', 'Th': 'Thorium', 'Ti': 'Titanium', 'Tl': 'Thallium',
    'Tm': 'Thulium', 'Ts': 'Tennessine', 'U': 'Uranium', 'V': 'Vanadium',
    'W': 'Tungsten', 'Xe': 'Xenon', 'Y': 'Yttrium', 'Yb': 'Ytterbium',
    'Zn': 'Zinc', 'Zr': 'Zirconium'
}

def fetch_arxiv_papers(keywords, max_results=50):
    base_url = 'http://export.arxiv.org/api/query?'
    all_papers = []

    for symbol, name in tqdm(ELEMENTS.items(), desc="Fetching arXiv papers"):
        query = f'all:"{name}" OR all:"{symbol}"'
        params = {
            'search_query': query,
            'start': 0,
            'max_results': max_results,
            'sortBy': 'relevance',
            'sortOrder': 'descending'
        }

        try:
            response = requests.get(base_url, params=params)
            feed = feedparser.parse(response.content)

            for entry in feed.entries:
                paper_data = {
                    'title': entry.title,
                    'authors': [author.name for author in entry.authors],
                    'abstract': entry.summary,
                    'published': entry.published,
                    'pdf_url': None,
                    'source': 'arXiv'
                }

                for link in entry.links:
                    if link.type == 'application/pdf':
                        paper_data['pdf_url'] = link.href.replace('http://', 'https://')
                        break

                all_papers.append(paper_data)

            time.sleep(1)
        except Exception as e:
            print(f"Error for {symbol}: {e}")
            continue

    df = pd.DataFrame(all_papers)
    df.to_csv('/content/data/papers/arxiv_papers.csv', index=False)
    print(f"Saved {len(df)} arXiv papers")
    return df

# material science textbooks
def download_textbooks():
    textbooks = [
        {
            "title": "Materials Science and Engineering - An Introduction (9th Ed) - Callister",
            "url": "https://anupturnedworld.wordpress.com/wp-content/uploads/2016/06/callister-materials-science-and-engineering.pdf",
            "author": "William D. Callister"
        },
        {
            "title": "The Science and Engineering of Materials (7th Ed) - Askeland",
            "url": "https://anupturnedworld.wordpress.com/wp-content/uploads/2016/06/askeland-the-science-and-engineering-of-materials.pdf",
            "author": "Donald R. Askeland"
        },
        {
            "title": "Introduction to Materials Science for Engineers (8th Ed) - Shackelford",
            "url": "https://industri.fatek.unpatti.ac.id/wp-content/uploads/2019/03/060-Introduction-to-Materials-Science-for-Engineers-James-F.-Shackelford-Edisi-8-2015.pdf",
            "author": "James F. Shackelford"
        },
        {
            "title": "Mechanical Behavior of Materials (2nd Ed)",
            "url": "https://ceimusb.wordpress.com/wp-content/uploads/2015/04/mechanicalbehaviorofmaterialshosford.pdf",
            "author": "Thomas H. Courtney"
        },
        {
            "title": "Phase Transformations in Metals and Alloys - Porter & Easterling",
            "url": "https://gateformme.wordpress.com/wp-content/uploads/2017/04/phase-transformations-in-metals-and-alloys.pdf",
            "author": "David A. Porter, Kenneth E. Easterling"
        },
        {
            "title": "Nanomaterials and Nanochemistry - Bréchignac",
            "url": "https://fredrol.folk.ntnu.no/Nanomaterials%20and%20Nanochemistry.pdf",
            "author": "Catherine Bréchignac"
        }
    ]

    downloaded = []

    def download_book(book):
        try:
            title = book['title'].replace(' ', '_').replace('/', '_')
            filename = f"/content/data/textbooks/{title}.pdf"

            if os.path.exists(filename):
                book['local_path'] = filename
                downloaded.append(book)
                return

            response = requests.get(book['url'], stream=True, timeout=30)
            if response.status_code == 200:
                with open(filename, 'wb') as f:
                    for chunk in response.iter_content(1024):
                        f.write(chunk)

                book['local_path'] = filename
                downloaded.append(book)
                time.sleep(1)
        except Exception as e:
            print(f"Error downloading {book['title']}: {str(e)}")

    print("Downloading textbooks...")
    with ThreadPoolExecutor(max_workers=5) as executor:
        list(tqdm(executor.map(download_book, textbooks), total=len(textbooks)))

    df = pd.DataFrame(downloaded)
    df.to_csv('/content/data/textbooks/textbooks_metadata.csv', index=False)
    print(f"Downloaded {len(df)} textbooks")
    return df

# Main function
def main():
    print("Starting data collection (without Wikipedia)...")

    arxiv_df = fetch_arxiv_papers(list(ELEMENTS.values()))
    textbooks_df = download_textbooks()

    all_metadata = pd.concat([
        arxiv_df,
        textbooks_df.rename(columns={'title': 'title', 'author': 'authors'})
    ], ignore_index=True)

    all_metadata.to_csv('/content/data/combined_metadata.csv', index=False)

    print("\nData collection complete!")
    print(f"Total papers collected: {len(arxiv_df)}")
    print(f"Total textbooks: {len(textbooks_df)}")
    print("\nAll data saved to /content/data/")

if __name__ == "__main__":
    main()

!cp -r '/content/data/papers' '/content/drive/MyDrive/papers'

!cp -r '/content/data/textbooks' '/content/drive/MyDrive/textbooks'

!pip install --upgrade transformers

!pip show transformers

import pandas as pd
import numpy as np
import torch
from torch import nn
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    BertPreTrainedModel,
    BertModel,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding
)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("processed_data.csv")

df["text"] = df.apply(
    lambda r: f"Compound: {r['compound']}. Elements: {r['elements']}. Symmetry: {r['symmetry']}.",
    axis=1
)

continuous = ["density", "band_gap", "formation_energy_per_atom", "volume"]
categorical = ["is_metal", "is_magnetic"]

scaler = StandardScaler()
df[continuous] = scaler.fit_transform(df[continuous])
df[categorical] = df[categorical].astype(int)
df["labels"] = df[continuous + categorical].values.tolist()

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
datasets = DatasetDict({
    "train": Dataset.from_pandas(train_df[["text", "labels"]]),
    "test": Dataset.from_pandas(test_df[["text", "labels"]])
})

model_name = "m3rg-iitd/matscibert"  # MatSciBERT
tokenizer = AutoTokenizer.from_pretrained(model_name)
data_collator = DataCollatorWithPadding(tokenizer)

def tokenize_fn(ex):
    toks = tokenizer(ex["text"], truncation=True, padding="max_length", max_length=128)
    toks["labels"] = ex["labels"]
    return toks

tokenized = datasets.map(tokenize_fn, batched=True, remove_columns=["text", "labels"])

# multi-task model
class MultiTaskMatSciBERT(BertPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.bert = BertModel(config)
        hidden = config.hidden_size
        self.reg_heads = nn.ModuleList([nn.Linear(hidden, 1) for _ in continuous])
        self.cls_heads = nn.ModuleList([nn.Linear(hidden, 2) for _ in categorical])
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.init_weights()

    def forward(self, input_ids, attention_mask, labels=None):
        out = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled = self.dropout(out.pooler_output)

        # Predictions
        cont_preds = [h(pooled).squeeze(-1) for h in self.reg_heads]
        cat_preds = [h(pooled) for h in self.cls_heads]

        loss = None
        if labels is not None:
            labels = torch.tensor(labels, dtype=torch.float32, device=pooled.device)
            cont_labels = labels[:, : len(continuous)]
            cat_labels = labels[:, len(continuous) :].long()

            # Compute losses
            losses = []
            for i, pred in enumerate(cont_preds):
                losses.append(nn.MSELoss()(pred, cont_labels[:, i]))
            for i, pred in enumerate(cat_preds):
                losses.append(nn.CrossEntropyLoss()(pred, cat_labels[:, i]))
            loss = sum(losses) / len(losses)

        # Return in HF format
        return {
            "loss": loss,
            "logits": (torch.stack(cont_preds, dim=1), torch.stack([p for p in cat_preds], dim=1))
        }
model = MultiTaskMatSciBERT.from_pretrained(model_name)

args = TrainingArguments(
    output_dir="results",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=5,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="loss",

    # evaluation every N steps
    eval_strategy="steps",
    eval_steps=500,       # evaluating every 500 steps
    save_strategy="steps",
    save_steps=500,       # saving every 500 steps
    logging_dir="./logs",
    logging_steps=100
)
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized["train"],
    eval_dataset=tokenized["test"],
    data_collator=data_collator
)
trainer.train()

trainer.save_model("fine_tuned_matscibert_multi")
tokenizer.save_pretrained("fine_tuned_matscibert_multi")
import joblib; joblib.dump(scaler, "scaler.save")

print("✅ Fine-tuning complete. Model + tokenizer + scaler saved.")

!cp -r '/content/fine_tuned_matscibert_multi' '/content/drive/MyDrive/fine_tuned_matscibert_multi'

!cp '/content/scaler.save' '/content/drive/MyDrive/'

!cp -r '/content/logs' '/content/drive/MyDrive/logs'

from langchain.document_loaders import CSVLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.vectorstores import FAISS
from langchain.embeddings import HuggingFaceEmbeddings
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch
import os
import fitz  # PyMuPDF for PDF processing
import pdfplumber

textbooks_folder = "/content/drive/MyDrive/textbooks/"
pdf_files = [os.path.join(textbooks_folder, f) for f in os.listdir(textbooks_folder) if f.endswith('.pdf')]

def extract_text_from_pdf_fitz(pdf_path):
    try:
        doc = fitz.open(pdf_path)
        text = ""
        for page_num in range(doc.page_count):
            page = doc.load_page(page_num)
            text += page.get_text("text")
        return text
    except Exception as e:
        print(f"Error extracting text from {pdf_path}: {e}")
        return None

# extract text from a PDF using pdfplumber for better handling of tables
def extract_text_from_pdf_plumber(pdf_path):
    try:
        with pdfplumber.open(pdf_path) as pdf:
            text = ""
            for page in pdf.pages:
                text += page.extract_text()
            return text
    except Exception as e:
        print(f"Error extracting text from {pdf_path}: {e}")
        return None

# Extract text from all textbooks (PDFs)
docs = []
for pdf in pdf_files:
    text_fitz = extract_text_from_pdf_fitz(pdf)
    text_plumber = extract_text_from_pdf_plumber(pdf)
    if text_fitz:
        docs.append(text_fitz)
    elif text_plumber:
        docs.append(text_plumber)
    else:
        print(f"Failed to extract text from {pdf}")

print(f"Loaded {len(docs)} documents ✅")

papers_csv = "/content/drive/MyDrive/papers/arxiv_papers.csv"
csv_loader = CSVLoader(file_path=papers_csv, csv_args={'delimiter': ','})
docs.extend(csv_loader.load())

print(f"Loaded {len(docs)} documents after CSV loading ✅")

from langchain.schema import Document
from langchain.text_splitter import RecursiveCharacterTextSplitter


documents = [Document(page_content=str(text)) for text in docs]

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100,
)

splitted_docs = splitter.split_documents(documents)

print(f"Split into {len(splitted_docs)} chunks ✅")

# ========================
# 3. MatSciBERT Embedding Class
# ========================
from transformers import AutoModel, AutoTokenizer
from typing import List
import torch
import numpy as np
from sklearn.decomposition import PCA
import torch
import numpy as np
from transformers import AutoTokenizer, AutoModel
from sklearn.decomposition import PCA

class MatSciBERTEmbeddings:
    def __init__(self, model_path: str, device: str = None, whiten: bool = False):
        self.device = device or ('cuda' if torch.cuda.is_available() else 'cpu')
        self.tokenizer = AutoTokenizer.from_pretrained(model_path)
        self.model = AutoModel.from_pretrained(model_path, output_hidden_states=True).to(self.device)
        self.model.eval()
        self.whiten = whiten
        self.pca = None

    def _compute_embeddings(self, texts):
        inputs = self.tokenizer(
            texts,
            padding=True,
            truncation=True,
            return_tensors="pt",
            max_length=512
        )
        inputs = {k: v.to(self.device) for k, v in inputs.items()}

        with torch.no_grad():
            outputs = self.model(**inputs)
            hidden_states = outputs.hidden_states

        # Take [CLS] token from last two layers
        cls_last = hidden_states[-1][:, 0, :]
        cls_second = hidden_states[-2][:, 0, :]
        embeddings = (cls_last + cls_second) / 2.0

        return embeddings.cpu().numpy()

    def embed_documents(self, texts, batch_size=16):
        all_embs = []
        for i in range(0, len(texts), batch_size):
            batch_texts = texts[i:i+batch_size]
            embs = self._compute_embeddings(batch_texts)
            all_embs.append(embs)

        all_embs = np.vstack(all_embs)

        if self.whiten:
            if self.pca is None:
                self.pca = PCA(whiten=True)
                all_embs = self.pca.fit_transform(all_embs)
            else:
                all_embs = self.pca.transform(all_embs)

        norms = np.linalg.norm(all_embs, axis=1, keepdims=True)
        norms[norms == 0] = 1.0
        all_embs = all_embs / norms

        return all_embs.tolist()

    def embed_query(self, text):
        emb = np.array(self.embed_documents([text]))
        return emb[0]

# ========================
# 4. Initialize Embeddings
# ========================
matscibert_embed = MatSciBERTEmbeddings(
    model_path="/content/drive/MyDrive/fine_tuned_matscibert_multi",
    whiten=False
)

# ========================
# 5. Build and Save FAISS VectorDB
# ========================
vectordb = FAISS.from_documents(
    splitted_docs,
    embedding=matscibert_embed
)

vectordb.save_local("/content/drive/MyDrive/material_rag_db_faiss_new/")
print("Vector DB built and saved ✅")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app_new.py
# import torch
# 
# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# print("✅ Using device:", device)
# 
# 
# 
# 
# from langchain.document_loaders import CSVLoader
# from langchain.text_splitter import RecursiveCharacterTextSplitter
# from langchain.vectorstores import FAISS
# from langchain.embeddings import HuggingFaceEmbeddings
# from sentence_transformers import SentenceTransformer
# from transformers import AutoTokenizer, AutoModelForSequenceClassification
# import torch
# import os
# import fitz  # PyMuPDF for PDF processing
# import pdfplumber
# 
# 
# # ========================
# # 3. MatSciBERT Embedding Class
# # ========================
# from transformers import AutoModel, AutoTokenizer
# from typing import List
# import torch
# import numpy as np
# from sklearn.decomposition import PCA
# import torch
# import numpy as np
# from transformers import AutoTokenizer, AutoModel
# from sklearn.decomposition import PCA
# 
# class MatSciBERTEmbeddings:
#     def __init__(self, model_path: str, device: str = None, whiten: bool = False):
#         self.device = device or ('cuda' if torch.cuda.is_available() else 'cpu')
#         self.tokenizer = AutoTokenizer.from_pretrained(model_path)
#         self.model = AutoModel.from_pretrained(model_path, output_hidden_states=True).to(self.device)
#         self.model.eval()
#         self.whiten = whiten
#         self.pca = None
# 
#     def _compute_embeddings(self, texts):
#         inputs = self.tokenizer(
#             texts,
#             padding=True,
#             truncation=True,
#             return_tensors="pt",
#             max_length=512
#         )
#         inputs = {k: v.to(self.device) for k, v in inputs.items()}
# 
#         with torch.no_grad():
#             outputs = self.model(**inputs)
#             hidden_states = outputs.hidden_states
# 
#         # Take [CLS] token from last two layers
#         cls_last = hidden_states[-1][:, 0, :]
#         cls_second = hidden_states[-2][:, 0, :]
#         embeddings = (cls_last + cls_second) / 2.0
# 
#         return embeddings.cpu().numpy()
# 
#     def embed_documents(self, texts, batch_size=16):
#         all_embs = []
#         for i in range(0, len(texts), batch_size):
#             batch_texts = texts[i:i+batch_size]
#             embs = self._compute_embeddings(batch_texts)
#             all_embs.append(embs)
# 
#         all_embs = np.vstack(all_embs)
# 
#         if self.whiten:
#             if self.pca is None:
#                 self.pca = PCA(whiten=True)
#                 all_embs = self.pca.fit_transform(all_embs)
#             else:
#                 all_embs = self.pca.transform(all_embs)
# 
#         norms = np.linalg.norm(all_embs, axis=1, keepdims=True)
#         norms[norms == 0] = 1.0
#         all_embs = all_embs / norms
# 
#         return all_embs.tolist()
# 
#     def embed_query(self, text):
#         emb = np.array(self.embed_documents([text]))
#         return emb[0]
# 
# # ========================
# # 4. Initialize Embeddings
# # ========================
# matscibert_embed = MatSciBERTEmbeddings(
#     model_path="/content/drive/MyDrive/fine_tuned_matscibert_multi",
#     whiten=False
# )
# 
# 
# # hf api
# 
# #!huggingface-cli login
# 
# 
# import google.generativeai as genai
# 
# # Initialize Gemini model
# genai.configure(api_key="your-api-key")  # <-- replace with your real Gemini API key
# gemini_model = genai.GenerativeModel("gemini-1.5-pro")  # you can use "gemini-1.5-pro" (best version)
# def ask_gemini(prompt):
#     response = gemini_model.generate_content(
#         prompt,
#         generation_config={
#             "temperature": 0.3,  # keep it low for material science accuracy
#             "top_p": 0.9,
#         }
#     )
#     return response.text
# 
# 
# 
# vectordb = FAISS.load_local(
#     "/content/drive/MyDrive/material_rag_db_faiss_new/",
#     embeddings=matscibert_embed.embed_query,
#     allow_dangerous_deserialization=True
# )
# 
# 
# from typing import List, Dict, Any
# import re
# 
# class MaterialRAGSystem:
#     def __init__(self, vectordb, matscibert_embed):
#         self.vectordb = vectordb
#         self.embedder = matscibert_embed
# 
#     def extract_materials(self, text: str) -> List[str]:
#         patterns = [
#             r"[A-Z][a-z]?\d*[A-Z][a-z]?\d*",  # Binary/ternary compounds
#             r"[A-Z][a-z]?\d*",                # Single elements
#             r"[A-Z][a-z]?_\d*[A-Z][a-z]?\d*",  # Doped materials
#         ]
#         materials = []
#         for pattern in patterns:
#             materials.extend(re.findall(pattern, text))
#         return list(set(materials))
# 
#     def retrieve_context(self, query: str, k: int = 5) -> List[Dict[str, Any]]:
#         query_embedding = self.embedder.embed_query(query)
#         docs_and_scores = self.vectordb.similarity_search_with_score_by_vector(query_embedding, k=k)
# 
#         results = []
#         for doc, score in docs_and_scores:
#             results.append({
#                 "content": doc.page_content,
#                 "score": float(score),
#                 "source": doc.metadata.get("source", "unknown")
#             })
#         return results
# 
#     def generate_response(self, query: str) -> str:
#         context_docs = self.retrieve_context(query)
# 
#         context_str = "\n\n".join([
#             f"SOURCE {i+1} (Relevance: {doc['score']:.2f}):\n{doc['content']}"
#             for i, doc in enumerate(context_docs)
#         ])
# 
#         prompt = f"""
# [Materials Science Expert System]
# 
# You are an expert materials science assistant. Your goal is to answer the user's question accurately and comprehensively based on the provided context and your knowledge.
# 
# Instructions:
# 1. Cite sources (e.g., SOURCE 1) when using specific facts.
# 2. For material substitutions, identify the most appropriate substitutes without recommending the original material.
# 3. Highlight uncertainties if any.
# 4. Compare and summarize properties across sources.
# 5. Provide explanations for mechanisms behind properties when possible.Use context and your knowledge to answer the question.
# 6. Avoid repetition; synthesize information if multiple sources mention similar facts.
# 
# Context Documents:
# {context_str}
# 
# Question: {query}
# 
# Answer:
# """
#         return prompt
# 
# rag_system = MaterialRAGSystem(vectordb, matscibert_embed)
# 
# from pyngrok import ngrok
# 
# # Replace with your ngrok authentication token
# ngrok.set_auth_token("your-token")
# 
# 
# 
# #Streamlit App for Material Science Chat
# 
# import streamlit as st
# 
# def material_science_chat_streamlit(rag_system):
#     st.set_page_config(page_title="Materials Science Expert Chat", page_icon="🧪", layout="wide")
# 
#     st.title("🧪 Materials Science Expert Chatbot")
#     st.markdown("""
#     Specialized in:
#     - **Material property prediction**
#     - **Composition design**
#     - **Quantum-aware substitutions**
# 
#     Type your question below 👇
#     """)
# 
#     if "chat_history" not in st.session_state:
#         st.session_state.chat_history = []
# 
#     query = st.text_input("🎯 Your materials science question:", key="input_text")
# 
#     if query:
#         st.session_state.chat_history.append(("User", query))
# 
#         with st.spinner("🔍 Analyzing your question..."):
#             try:
#                 if any(word in query.lower() for word in ["substitute", "replace", "alternative"]):
#                     info = "Checking for material substitutions..."
#                 elif "property" in query.lower():
#                     info = "Evaluating material properties..."
#                 elif "synthes" in query.lower() or "make" in query.lower():
#                     info = "Reviewing synthesis protocols..."
#                 else:
#                     info = "Processing your query..."
# 
#                 st.info(info)
# 
#                 # Generate system prompt
#                 prompt = rag_system.generate_response(query)
#                 response = ask_gemini(prompt)
# 
#                 st.session_state.chat_history.append(("Bot", response))
# 
#             except Exception as e:
#                 st.error(f"⚠️ Error: {str(e)}")
# 
#     # Display chat history
#     st.markdown("---")
#     for sender, message in st.session_state.chat_history:
#         if sender == "User":
#             st.markdown(f"**👤 You:** {message}")
#         else:
#             st.markdown(f"**🤖 MaterialsBot:** {message}")
# 
#     st.markdown("---")
#     st.caption("🚀 Powered by Fine-tuned MatSciBERT + FAISS RAG System")
# 
# # Call the Streamlit app
# material_science_chat_streamlit(rag_system)
#

#!pip install streamlit pyngrok
from pyngrok import ngrok

# Set authentication token if you haven't already done so
ngrok.set_auth_token("token")

# Start Streamlit server on a specific port
!nohup streamlit run app_new.py --server.port 5011 &
for tunnel in ngrok.get_tunnels():
    print("Closing tunnel:", tunnel.public_url)
    ngrok.disconnect(tunnel.public_url)
# Start ngrok tunnel to expose the Streamlit server
ngrok_tunnel = ngrok.connect(addr='5011', proto='http', bind_tls=True)

# Print the URL of the ngrok tunnel
print(' * Tunnel URL:', ngrok_tunnel.public_url)